report.pdf: report.tex plot1.png plot2.png
	latexmk -pdf

plot1.png: makedata.py countflights.py
	python plot1.py

plot2.png: makedata.py countflights.py
	python plot2.py

.PHONY: clean almost_clean

clean: almost_clean
	rm report.pdf
	rm plot1.png
	rm plot2.png

almost_clean:
	
	 
